### ISSUE TITLE
replace/add: JSON encoding omits Value if null

### ISSUE THREAD

**Issue by tmichaud314** [mattbaird/jsonpatch#2]
Hi @mattbaird,

[RFC 6902 - 4.3 replace](https://tools.ietf.org/html/rfc6902#section-4.3) says:
```
[...] The operation object MUST contain a "value" member whose content specifies the replacement value. [...]
```
But the [JsonPatchOperation struct](https://github.com/mattbaird/jsonpatch/blob/master/jsonpatch.go#L15) JSON encoding for `Value` omits it if it's null:
```
type JsonPatchOperation struct {
	Operation string      `json:"op"`
	Path      string      `json:"path"`
	Value     interface{} `json:"value,omitempty"`
}
```

Proposing JsonPatchOperation implement json.Marshaller so it can emit a `null` value for the `replace` operation.  Wdyt?

Thanks!

**Comment by tmichaud314** [comment]
@mattbaird Do you plan to do upkeep on this repo/project?

**Comment by mattbaird** [comment]
hi @tmichaud314 yes, however I work at an enterprise company and it's q4, so things are a bit nutty.
I will test your patch this weekend.

**Comment by tmichaud314** [comment]
Here is a [PR for your review](https://github.com/mattbaird/jsonpatch/pull/3).  No rush and thanks!

**Comment by mattbaird** [comment]
Thanks for contributing!
